[bastion]
192.168.50.10 public_ip=158.160.105.45 ansible_user=mastervm
    
[web_servers]
192.168.10.10 ansible_user=mastervm
192.168.10.20 ansible_user=mastervm

[web_server_1]
192.168.10.10 ansible_user=mastervm

[web_server_2]
192.168.10.20 ansible_user=mastervm

[zabbix]
192.168.50.20 public_ip=89.169.159.72 ansible_user=mastervm

[zabbix_server]
192.168.50.20 ansible_user=mastervm
    
[elastic_server]
192.168.10.30 ansible_user=mastervm

[kibana_server]
192.168.50.30 public_ip=158.160.113.100 ansible_user=mastervm

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -p 22 -W %h:%p -q mastervm@158.160.105.45"'
zabbix_ext_ip=89.169.159.72
zabbix_int_ip=192.168.50.20

